[build]
  base = "phi-website"
  publish = "dist"
  command = "npm run build"

[[functions]]
  name = "server"
  include = ["public/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
